## ##YAML Template
default: --profile html_report
html_report: --format progress
             --format html
             --out=features/output/features_report.html
bvt: --tags @Sanity
applicationURL: https://demo.cyclos.org/
time: Time.now.strftime("%Y-%m-%d %H%M")
